baseURL: '/'
languageCode: en-us
title: Cloud Native Rejekts {{< params event.edition >}}
theme: rejekts

menu:
  # Main controls the buttons show in the nmain nav bar
  # You can show / hide them by (un)commenting them here.
  # The ordering of the menu items is controlled with the `weight` property
  main:
    # - identifer: schedule
    #   name: Schedule
    #   url: "#schedule"
    #   weight: -110
    # - identifer: speakers
    #   name: Speakers
    #   url: "#speakers"
    #   weight: -110
    # - identifer: program_committee
    #   name: Program Committee
    #   url: "#program_committee"
    #   weight: -100
    # - identifer: venue
    #   name: Venue
    #   url: "#venue"
    #   weight: -100
    # - identifer: tickets
    #   name: Tickets
    #   url: "#tickets"
    #   weight: -95
    - identifer: conduct
      name: Code of Conduct
      url: "#conduct"
      weight: -90
    # - identifer: participation
    #   name: CFP
    #   url: "#participation"
    #   weight: -85
    - identifer: sponsorship
      name: Sponsors
      url: "#sponsor"
      weight: -80

permalinks:
  announcements: /announcements/:year/:month/:title/
  events: /events/:contentbasename/

disableKinds:
- taxonomy
- term

buildFuture: false

params:
  event:
    # state controls the state of the CFP button. Possible values are: pending, cfpopen, cfpclosed, cfppublished, archived
    state: pending
    city: Barcelona
    edition: EU 2027
    code: |
      {{< params event.edition replace " " "" >}}
    description: |
      Cloud Native Rejekts {{< params event.edition >}} is the b-side conference giving a second chance to the many
      wonderful, but rejected talks leading to KubeCon + CloudNativeCon.

      Cloud Native Rejekts {{< params event.edition >}} will be an in-person conference. We hope to see you in {{< params event.city >}}, on {{< params event.schedule.datetime month >}} {{< params event.schedule.datetime day >}} on the heels of KubeCon + CloudNativeCon.

      See you in {{< params event.schedule.datetime month >}}!

    prospectus: Rejekts_Sponsorship_Prospectus_{{< params event.edition replace " " "_" >}}.pdf
    sponsor:
      hide: false
      link:
        hide: false
      pitch: |
        Sponsoring Cloud Native Rejekts not only supports the wider cloud native
        community leading into the week's main event. It's also a chance to present your company, product, and messaging
        in a more relaxed and fun setting than the typical trade show. Want to support the Cloud Native Rejekts {{< params event.edition >}}?

    # This controls the ticket button being functional or not. Comment out to disable tickets until available.
    # tickets_url: https://pretix.eu/rejekts/rejektseu26/

    # If admission is set to free the ticket prices aren't show, otherwise set the price tiers below
    admission_free: true
    # tickets:
    #   - type: academic
    #     price:
    #       early:
    #       standard:
    #       late:
    #   - type: professional
    #     price:
    #       early:
    #       standard:
    #       late:
    #   - type: corporate
    #     price:
    #       early:
    #       standard:
    #       late:
    #   - type: diversity
    #     price:
    #       early: $0
    #       standard: $0
    #       late: $0

    schedule:
      # Once the schedule is available uncomment this line and set to URL
      # link: https://cloud-native-rejekts-eu-2026.sessionize.com/schedule/day/20260321
      datetime: 2027-03-13 09:30:00
      days:
        - slots:
          - title: Registration
            time: 9:30 AM
          - title: Opening Remarks
            time: 10:00 AM
          - title: Talks
            time: 10:20 AM
          - title: Closing Remarks
            time: 6:45 PM

    venue:
      hide: true
      showImages: true
      name: Miro HQ
      address: Fred. Roeskestraat 100, 1076 ED Amsterdam
      city: Amsterdam, Netherlands
      # website: https://studentcenter.gatech.edu/academy-medicine/space/entire-building
      maplink: https://maps.app.goo.gl/KFzxgKbdyo7wJEUn7
      embedded_map: |
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2437.5973372146077!2d4.8587311!3d52.341450599999995!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c5e3a6aea737b3%3A0x9d2b23201bf6e8e5!2sMiro!5e0!3m2!1sen!2suk!4v1771253796587!5m2!1sen!2suk" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

    # sponsors:
    #   - type: Champion
    #     sponsors: []
    #   - type: Partner
    #     sponsors:
    #     - name: ProsperOps
    #       link: https://www.prosperops.com
    #       logo: ProsperOps.png
    #     - name: Edera
    #       link: https://edera.dev
    #       logo: Edera.svg
    #     - name: Miro
    #       link: https://miro.com/
    #       logo: Miro.png
    #   - type: Supporter
    #     sponsors:
    #     - name: Microsoft
    #       link: https://microsoft.com/
    #       logo: MS-Azure.png
    #   - type: Community
    #     sponsors:
    #     - name: Isovalent
    #       link: https://isovalent.com/
    #       logo: isovalent.png
    #     - name: Artem
    #       link: https://medium.com/@Artem
    #       logo: artem.png
    #     - name: FikaWorks
    #       link: https://fika.works
    #       logo: FikaWorks.png
    #   - type: Media
    #     sponsors:
    #     - name: CloudNative.Now
    #       link: https://cloudnative.now
    #       logo: CloudNativeNow.png
    #     - name: Cloud Native Days Romania
    #       link: https://cloudnativedays.ro
    #       logo: CloudNativeDaysRomania.png


  social:
    - title: Twitter
      url: 'https://twitter.com/rejektsio'
      image: 'twitter-icon'
    - title: Bluesky
      url: 'https://bsky.app/profile/rejekts.io'
      image: 'bluesky-icon'
    - title: Mastodon
      url: 'https://hachyderm.io/@Rejekts'
      image: 'mastodon-icon'
    - title: LinkedIn
      url: 'https://www.linkedin.com/company/cloud-native-rejekts/'
      image: 'linkedin-icon'
    - title: Instagram
      url: 'https://www.instagram.com/Rejektsio/'
      image: 'instagram-icon'
    - title: email
      url: "mailto:info@rejekts.io"
      image: 'email-icon'

  hero:
    title: Recycle your KubeCon talk here!
    hashtag: |
      rejekts{{< params event.code >}}
    image: hero-img.svg
    description:  |
      Cloud Native Rejekts EU offers attendees a weekend of 'unaccepted' talks leading into
      KubeCon + CloudNativeCon. It provides a stage for some of the 89% of talks rejected by KubeCon + CloudNativeCon.

  # This controls the details shown for the CFP, primarily the dates it opens, closes and announced
  participation:
    opens: Wednesday, December 9
    closes: Sunday, January 17
    notifications: Friday, February 5
    schedule: Monday, February 8
    opens_comment: Opens after KubeCon notifications go out
    closes_comment: Two weeks after CFP opens
    description:  |
      Cloud Native Rejekts welcomes the rejected proposals from KubeCon + CloudNativeCon or new ones
      that cover super fresh topics. We offer slots for 30min full-length talks and 5min
      lightning talks. We welcome topics about...
    # link: https://cfp.cloud-native.rejekts.io/cloud-native-rejekts-atlanta-na-atlanta-2025/schedule/
    # volunteer_form: https://forms.gle/R1sSnytKmMXBBmDR9
    topics: [
      "core concepts",
      "open-source components + tooling",
      "user experiences",
      "security",
      "new developments + experiments",
      "etc."
    ]

  # This controls showing of a video at the bottom of the event page
  promo:
    video:
      heading: "Video of past events"
      link: https://www.youtube.com/embed/ZJhnx2kgh80

  # This controls showing a carousel image gallery at the bottom of the page
  media:
    city: Amsterdam, The Netherlands
    gallery:
      link: https://www.flickr.com/photos/181798830@N03/albums/72177720332862399
      thumbnail: https://live.staticflickr.com/65535/55181531360_923214b621_b.jpg
    promo:
      video:
